#!/bin/sh
# postinst script for arrow-judge-web

set -e

case "$1" in
    configure)
        if [ -d /etc/apache2/mods-enabled ] && [ -e /etc/apache2/mods-available/rewrite.load ] && [ ! -e /etc/apache2/mods-enabled/rewrite.load ]; then
            ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load
        fi
        if [ -d /etc/apache2/conf.d ] && [ ! -e /etc/apache2/conf.d/arrow-judge.conf ]; then
                    ln -s /etc/arrow-judge/apache.conf /etc/apache2/conf.d/arrow-judge.conf
            if [ -x /usr/sbin/invoke-rc.d ]; then
                invoke-rc.d apache2 reload 3>/dev/null || true
            else
                /etc/init.d/apache2 reload 3>/dev/null || true
            fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
